#!/bin/bash

function logo() {
    bash <(curl -s https://raw.githubusercontent.com/CPITMschool/Scripts/main/logo.sh)
}

function printGreen {
    echo -e "\e[1m\e[32m${1}\e[0m"
}

function printRed {
  echo -e "\e[1m\e[31m${1}\e[0m"
}

function check {
    while true; do
        printGreen "Виберіть, що ви хочете переглянути:"
        echo "1) Переглянути зайняті порти."
        echo "2) Перегляти перелік нод панелі та портів які вони використовують"
        echo "3) Вийти."
        read choice

        if [[ $choice == "1" ]]; then
            clear
            logo
            printGreen "У третьому стовпці ви побачите список портів, які вже використовуються на вашому сервері."
            netstat -tuln | awk '{ if ($NF == "LISTEN") print $0; else if ($NF ~ /^[0-9]+\/.*/) print "\033[1;31m"$0"\033[0m"; else print "\033[1;33m"$0"\033[0m" }'
        elif [[ $choice == "2" ]]; then
            clear
            logo
            printGreen "Перелік нод з панелі та стандартних портів які використовує кожна з них:"
            # Решта виводу вашого переліку нод
            # ...
            printRed "Lava,DeFund,Nibiru використовують одні і ті ж самі порти, тому при встановлені з запропонованого списку вибирайте різний набір портів"
            printRed "Перед встановленням будь-якої ноди, перевіряйте чи зайняті порти які буде використовувати ця нода, через цю панель."
        elif [[ $choice == "3" ]]; then
            break
        else
            echo "Невірний вибір."
        fi
    done
}


clear
logo
check
