#!/bin/bash

function logo() {
    bash <(curl -s https://raw.githubusercontent.com/CPITMschool/Scripts/main/logo.sh)
}

function printGreen {
    echo -e "\e[1m\e[32m${1}\e[0m"
}

function printRed {
    echo -e "\e[1m\e[31m${1}\e[0m"
}

function is_port_taken {
    local port=$1
    if netstat -tuln | awk -v p=":${port}\$" '$0 ~ p {exit 1}'; then
        return 0
    else
        return 1
    fi
}

function check {
    while true; do
        printGreen "Виберіть, що ви хочете переглянути:"
        echo "1) Переглянути зайняті порти."
        echo "2) Перегляти перелік нод панелі та портів які вони використовують"
        echo "3) Вийти."
        read choice

        if [[ $choice == "1" ]]; then
            clear
            logo
            printGreen "У третьому стовпці ви побачите список портів, які вже використовуються на вашому сервері."
            printRed "Наприклад::::30333 - використовується порт 30333"
            printRed "Наприклад::::9090 - використовується порт 9090"
            printRed "Наприклад 127.0.0.1:26657 - використовується порт 26657"

            netstat -tuln | awk 'NR>2 {print $4}' | awk -F ':' '{print $NF}' | sort -u | while read -r port; do
                if is_port_taken "$port"; then
                    printRed "$port - використовується порт $port"
                else
                    echo "$port"
                fi
            done
        elif [[ $choice == "2" ]]; then
            # ...
        elif [[ $choice == "3" ]]; then
            break
        else
            echo "Невірний вибір."
        fi
    done
}


clear
logo
check
